customercommandside:
  image: java:openjdk-8u91-jdk
  command: java -jar /app/customers-command-side-service.jar
  ports:
    - "8081:8080"

orderhistoryqueryside:
  image: java:openjdk-8u91-jdk
  command: java -jar /app/order-history-query-side-service.jar
  ports:
    - "8082:8080"
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/clients_and_orders

ordercommandside:
  image: java:openjdk-8u91-jdk
  command: java -jar /app/orders-command-side-service.jar
  ports:
    - "8083:8080"

mongodb:
  image: mongo:3.0.4
  hostname: mongodb
  command: mongod --smallfiles
  ports:
    - "27017:27017"
