customercommandside:
  extends:
    file: docker-compose-common.yml
    service: customercommandside
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

orderhistoryqueryside:
  extends:
    file: docker-compose-common.yml
    service: orderhistoryqueryside
  links:
    - mongodb
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

ordercommandside:
  extends:
    file: docker-compose-common.yml
    service: ordercommandside
  links:
      - customercommandside
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

mongodb:
  extends:
    file: docker-compose-common.yml
    service: mongodb
