customercommandside:
  extends:
    file: docker-compose-common.yml
    service: customercommandside
  volumes:
    - ./customers-command-side-service/build/libs:/app
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

orderhistoryqueryside:
  extends:
    file: docker-compose-common.yml
    service: orderhistoryqueryside
  volumes:
    - ./order-history-query-side-service/build/libs:/app
  links:
    - mongodb
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

ordercommandside:
  extends:
    file: docker-compose-common.yml
    service: ordercommandside
  volumes:
    - ./orders-command-side-service/build/libs:/app
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

mongodb:
  extends:
    file: docker-compose-common.yml
    service: mongodb
