version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-examples-java-customers-and-orders
    steps:
      - checkout
      - restore_cache:
          key: eventuate-examples-java-customers-and-orders-{{ checksum "build.gradle" }}
      - run: TERM=dumb (cd common-contracts ; ./mvnw install)
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: eventuate-examples-java-customers-and-orders-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./build-and-test-all-eventuate-local.sh
      - run: TERM=dumb ./build-and-test-all.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
