customercommandside:
  build: ../customers-service/
  ports:
    - "8081:8080"
  external_links:
    - eventuateexamplesjavacustomersandorders_mysql_1:mysql
    - eventuateexamplesjavacustomersandorders_kafka_1:kafka
    - eventuateexamplesjavacustomersandorders_zookeeper_1:zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
